services:
  backend:
    container_name: backend
    build: ../backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
    ports:
      - "8105:8000"
    networks:
      - foodgram_network

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
    networks:
      - foodgram_network

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    networks:
      - foodgram_network

  db:
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - foodgram_network

volumes:
  postgres_data:
  static:
  media:

networks:
  foodgram_network:
    driver: bridge